# Site
repository: rujealfon/rujealfon.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Ruje Alfon
title: Web Developer
email: alfonruje@gmail.com
phone: +63-9053801178
website: http://rujealfon.github.io

# Social links
github_username:  rujealfon
facebook_username: rujealfon
instagram_username: parengruje
linkedin_username: rujealfon

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  A technically savvy web developer, has a long track record of creating dynamic, rich and interesting web portals, and of providing long term solutions to front-end problems. Working in a fast paced environment and producing a high volume of websites. Responsible for participating in the full life cycle of new website development projects, and for implement and maintaining best practice procedures in all areas of work. Also in charge of writing, developing and managing the content of websites. Designing, coding and modifying websites, from layout to function and according to a client's specifications. Strive to create visually appealing sites that feature user-friendly design and clear navigation.
  
   - Highly proficient with Vue.js framework and its core principles such as components, reactivity, and the virtual DOM
   - Familiarity with the Vue.js ecosystem, including Vue CLI, Vuex, Vue Router, and Nuxt.js
   - Knowledge of functional programming and object-oriented programming paradigms
   - Ability to write efficient, secure, well-documented, and clean JavaScript code
   - Proficiency with modern development tools, like Babel, Webpack, and Git
   - Experience with both consuming and designing RESTful APIs
   - Good understanding of HTML5 and CSS3, including Sass
   - JavaScript
   - VueJs
   - JQuery
   - HTML
   - HTML5
   - CSS
   - CSS3
   - Web Programming Skills
   - Cross-Browser Compatibility
   - Web User Interface Design (UI)
   - Security Principles
   - Object-Oriented Design
   - Web Services (REST)
   - Cloud Infrastructure
   - Database Administration
   - Teamwork

# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Systems Administration – Setting up, configuring and customizing Linux systems remotely on a shared environment, VPS, and cloud infrastructure. Installing, configuring and customizing Apache, NginX, PHP and Node builds. Setting up and configure SSL and server health scripts. Writing scalable and cost effective auto-scaling scripts and implementation.

  Database Administration – Setting up and configuring MySQL remotely on a shared environment, VPS, or cloud infrastructure. Writing scalable backup scripts. Installing and configuring SQL databases. Optimizing database queries. Maintaining and migrating databases larger than 4GB. Creating and maintaining read/write replicas and shards. Writing scalable and cost effective auto-scaling scripts and implementation.

  Cache Administration – Setting up and configuring Redis, and Solr remotely on a VPS and cloud infrastructure. Writing scalable backup scripts. Optimizing search rules. Maintaining and migrating data larger than 4GB. Creating and maintaining read/write replicas and shards. Writing scalable and cost effective auto-scaling scripts and implementation.

  Version Control Management – Maintaining open source, private and personal GitHub repositories. Clearly describing commits and merges. Frequently comments on commits by others and contributes to the Open Source community. Follows the GIT or GitHub Flow. Effectively create version releases on GitHub and NPM.

  Open Source Management – Frequently answers questions regarding code created by the company with an open source license. Takes initiative in turning around quick fixes. Promotes the company's open source efforts through events, articles and word of mouth. Supports the companies open source initiatives.

  Quality Control and Continuous Integration – Setup and configure GitHub open source, private and personal repositories with Travis CI and Coveralls. Writes hooks from GitHub and Travis to staging and production environments. Recreate issues clearly. Strictly does not perform work on out of scope items unless authorized by the team lead or project manager. Identify problem sources and recommended absolutions. Escalates and asks for advice about issues when frequently. Uses GitHub issue tracking properly. Sets milestones to a set of issues. Replies to project managers and team leads frequently.

  Back End Development – Converts business requirements into objects, event and actions. Creates a usable interface to control objects. Converts events and actions to APIs. Writes code methodically for readability, scalability and reusability. Identifies potential security vulnerabilities and scalability problems before and during development. Documents on written code religiously. Primarily uses object oriented PHP and Node for backend development.

  API Development – Translate Facebook, Twitter, Google, PayPal and other popular global and local API documentations into code contributing to the company's open source libraries. Develops OAuth v2 and v3 specifications for authentication.

  Web Development – Creates SEO optimized and mobile responsive HTML5 with CSS3. Implementing Twitter Bootstrap in projects. Properly uses meta and header tags whenever possible. Alphabetizes CSS styles. Uses VueJs to develop interactions and user interfaces. Writes object oriented JavaScript. Applies objects, events and actions in a front end environment. Maintaining an HTML5 Boilerplate. Cases for browser quirks. Writes code using syncronous, require and promises. Writes code methodically for readability, scalability and reusability. Identifies potential security vulnerabilities and scalability problems before and during development. Documents on written code religiously.

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
